/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallasproyectoarquitectura;

import javax.swing.JPanel;
import generacionTablero.Timbiriche;


public class PantallaJuego extends javax.swing.JFrame {
    
   
    /**
     * Creates new form PantallaJuego
     */
    public PantallaJuego(int cantidadJugadores) {
       
        int cantidadCuadros=0;
        switch(cantidadJugadores){
            case 2:cantidadCuadros=10;break;
            case 3:cantidadCuadros=20;break;
            case 4:cantidadCuadros=10;break;
        
        }
        
       new Timbiriche(cantidadCuadros);
     //   initComponents();
       
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInterfaz = new javax.swing.JPanel();
        botonAbandonarPartida = new javax.swing.JButton();
        panelTablero = new javax.swing.JPanel();
        etiquetaTitulo = new javax.swing.JLabel();
        nombreJugador1 = new javax.swing.JLabel();
        nombreJugador2 = new javax.swing.JLabel();
        nombreJugador3 = new javax.swing.JLabel();
        nombreJugador4 = new javax.swing.JLabel();
        iconoJugador1 = new javax.swing.JLabel();
        iconoJugador2 = new javax.swing.JLabel();
        iconoJugador3 = new javax.swing.JLabel();
        iconoJugador4 = new javax.swing.JLabel();
        etiquetaTurnoTitul = new javax.swing.JLabel();
        etiquetaEnTurno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1200, 1200));

        panelInterfaz.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonAbandonarPartida.setText("Abandonar Partida");
        botonAbandonarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAbandonarPartidaActionPerformed(evt);
            }
        });
        panelInterfaz.add(botonAbandonarPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 350, 130, -1));

        panelTablero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelTableroLayout = new javax.swing.GroupLayout(panelTablero);
        panelTablero.setLayout(panelTableroLayout);
        panelTableroLayout.setHorizontalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 898, Short.MAX_VALUE)
        );
        panelTableroLayout.setVerticalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 898, Short.MAX_VALUE)
        );

        panelInterfaz.add(panelTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 900, 900));

        etiquetaTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        etiquetaTitulo.setText("Timbiriche");
        panelInterfaz.add(etiquetaTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        nombreJugador1.setText("Vacio");
        panelInterfaz.add(nombreJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 260, -1, -1));

        nombreJugador2.setText("Vacio");
        panelInterfaz.add(nombreJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 140, -1, -1));

        nombreJugador3.setText("Vacio");
        panelInterfaz.add(nombreJugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 180, -1, -1));

        nombreJugador4.setText("Vacio");
        panelInterfaz.add(nombreJugador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 220, -1, -1));

        iconoJugador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pantallasproyectoarquitectura/imagenes/avatar.png"))); // NOI18N
        panelInterfaz.add(iconoJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 260, -1, -1));

        iconoJugador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pantallasproyectoarquitectura/imagenes/avatar.png"))); // NOI18N
        panelInterfaz.add(iconoJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 140, -1, -1));

        iconoJugador3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pantallasproyectoarquitectura/imagenes/avatar.png"))); // NOI18N
        panelInterfaz.add(iconoJugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 180, -1, -1));

        iconoJugador4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pantallasproyectoarquitectura/imagenes/avatar.png"))); // NOI18N
        panelInterfaz.add(iconoJugador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 220, -1, -1));

        etiquetaTurnoTitul.setText("En Turno");
        panelInterfaz.add(etiquetaTurnoTitul, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 100, -1, -1));

        etiquetaEnTurno.setText("Vacio");
        panelInterfaz.add(etiquetaEnTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 100, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInterfaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInterfaz, javax.swing.GroupLayout.PREFERRED_SIZE, 1094, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAbandonarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAbandonarPartidaActionPerformed
        MenuPrincipal abrir = new MenuPrincipal();
        abrir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonAbandonarPartidaActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAbandonarPartida;
    private javax.swing.JLabel etiquetaEnTurno;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JLabel etiquetaTurnoTitul;
    private javax.swing.JLabel iconoJugador1;
    private javax.swing.JLabel iconoJugador2;
    private javax.swing.JLabel iconoJugador3;
    private javax.swing.JLabel iconoJugador4;
    private javax.swing.JLabel nombreJugador1;
    private javax.swing.JLabel nombreJugador2;
    private javax.swing.JLabel nombreJugador3;
    private javax.swing.JLabel nombreJugador4;
    private javax.swing.JPanel panelInterfaz;
    private javax.swing.JPanel panelTablero;
    // End of variables declaration//GEN-END:variables
}
